# Copyright Â© 2019, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

language: python

dist: xenial


stages:
  - flake8
  - test
  - name: create release
    if: tag IS present
  - name: upload documentation
    if: tag IS present
  - name: deploy to pypi
    if: tag IS present


matrix:

  allow_failures:
    - env: TOXENV=py36-flake8

  include:
    - python: 3.5
      env: TOXENV=py35-tests-codecov TOX_SKIP_MISSING_INTERPRETERS=False
    - python: 3.6
      env: TOXENV=py36-tests-codecov TOX_SKIP_MISSING_INTERPRETERS=False
    - python: 3.7
      env: TOXENV=py37-tests-codecov TOX_SKIP_MISSING_INTERPRETERS=False
    - python: 3.8
      env: TOXENV=py38-tests-codecov TOX_SKIP_MISSING_INTERPRETERS=False


    - stage: flake8
      python: 3.6
      env: TOXENV=py36-flake8


    - stage: create release
      python: 3.6
      install: pip install sphinx pyyaml
      script:
      - sphinx-build -Ean -b html -j auto -D todo_include_todos=0 ./doc ./doc/_build/html
      - pushd ./doc/_build/html ; zip -r ../../../${TRAVIS_TAG}-doc.zip . ; popd
      deploy:
        provider: releases
        skip_cleanup: true
        api_key: "$GITHUB_TOKEN"
        file: "${TRAVIS_TAG}-doc.zip"
        draft: true
        on:
          tags: true


    - stage: upload documentation
      python: 3.6
      install: pip install sphinx
      script:
      - sphinx-build -Ean -b html -j auto -D todo_include_todos=0 ./doc ./doc/_build/html
      - touch ./doc/_build/html/.nojekyll
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: "$GITHUB_TOKEN"
        keep_history: false
        local_dir: "./doc/_build/html"
        on:
          tags: true

    # Travis deploy: pypi settings started returning "Your build exited with 86."
    # Reverting to manual build and upload
    - stage: deploy to pypi
      python: 3.6
      install: pip install setuptools wheel twine
      env:
      - TWINE_USERNAME: "$PYPI_USERNAME"
      - TWINE_PASSWORD: "$PYPI_PASSWORD"
      script:
        - python setup.py sdist bdist_wheel
        - python -m twine upload dist/*
      on:
        tags: true


install:
  - pip install tox "virtualenv<20.0.0"  # workaround for pip issue:  https://github.com/pypa/virtualenv/issues/1551#issuecomment-584148133


script:
  - tox
