dist: xenial
language: python
cache: pip
python:
- '2.7'
- '3.4'
- '3.5'
- '3.7'
env:
- PYTHONPATH=$PYTHONPATH:./src
install:
- pip install -r test_requirements.txt
script:
- pytest
jobs:
  include:
  - stage: upload codecov results
    python: 3.6
    install:
    - pip install pytest pytest-cov codecov
    - pip install -r test_requirements.txt
    script:
    - pytest --cov=./
    - codecov
  - stage: create release
    if: tag is present
    python: 3.6
    install: pip install sphinx
    script:
    - sphinx-build -Ean -b html -j auto -D todo_include_todos=0 ./doc ./doc/_build/html
    - pushd ./doc/_build/html ; zip -r ../../../${TRAVIS_TAG}-doc.zip . ; popd
    deploy:
      provider: releases
      skip_cleanup: true
      api_key: "$GITHUB_TOKEN"
      file: "${TRAVIS_TAG}-doc.zip"
      draft: true
      on:
        tags: true
  - stage: upload documentation
    if: tag is present
    python: 3.6
    install: pip install sphinx
    script:
    - sphinx-build -Ean -b html -j auto -D todo_include_todos=0 ./doc ./doc/_build/html
    - touch ./doc/_build/html/.nojekyll
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: "$GITHUB_TOKEN"
      keep_history: false
      local_dir: "./doc/_build/html"
      on:
        tags: true
  - stage: deploy to pypi
    if: tag is present
    script:
    - 
    deploy:
      provider: pypi
      user:
        secure: BkSk3YOVq/wb10zg6ceI7NdymLWhuexH8WH2KHHVIBaZDeoo1Hfzm6bSwxIPlngN5737ubBgVXnCM7oSElPh9oQYhX6PyNPR2X9DshQCoM1iShIhdo3Wb9XYT0V/MZ6/yf9pqbirx1mQ7rM+xTs9lrw7OCgi1/fJXPmXc7Qv8DGfhT0y9SbsktIJoAPg4qjWuGbo/2Jm5l8UNmTp6N5brJO+C1cRp65fZ1LcJ6PeWK+0iIi+oLyMz74TYrVAh+eqIlbnB6ss7WBHw7Bh3Cr7QjyaH5dDBGkouPPUbkSy9tNDcLUERSKPPPAOtY53tADI6ap+2hLFMKFz1wuOBwrabbsxkbdTPNbd9sS6bMrdHajRwuE7WyFkKe4yd9JzmafrBzUsR+hjyjCDIBT9lwn9EIeWaKtbm2zOmh7EbQBhK2q71hc+8ZiDx42uWIpEZnCSkWJYyGHdHiy1kgPsqWnUOMxReIRSfqdrdkVBfA6F68nh5k9w06chSj81Tb/mAnf3xGI8r3EwqMlXfyo+bBCYK3NibaBYMy4xhUiH566cQ+1Rt6JdAaVZIgK6Euu7zas0szZKddXUelaLlc2VHUyoJR8gazVdK6V8hDJykZb85KYp0lWhd78v4ANsDzSjjxoO8YT43iwiFgHarjXN1Vnd9fixWinT3r3BCdUryetOQ1g=
      password:
        secure: UOnKL5rBTgv8ubh/0l+4BKEO1C89h/PF3y+Y6cq40881yQLkLItTDxYkWCf36m6L/IyOnACwn5kJziQuTUSgyzfN58TRBvjVagjdkDQtwObLZVoU5PX+aMLRF+D7djdIekiOvhvQ476UDUR8jL3FwcQU4QJ72KQJqNn/UohdQquDP91qlcr+XLN/rvLeJAdQ8brOjpansX5qbHuJey+9oGgl9cwAVapvGVzvxk46oDb8hSrWJXZZU5PeEkoOdtGnOUdmWTtjuPjjYA6Fk/jyk+3fSgolHqa4vjFLu2PfDK+hDSZY1JIAxqUGKRzj+O4J2cm5ChMOwB4FwkA+7ZUBptHKnAD+qD4Z2iDRvkVTGgOUsmwS25DAcoEM6t9j5bjozW1vgCiIjf51v6GplQC0rY/QpxVkDnNlLC9Ov+paj+3KgG+BI2S+gjb9XD9tgnsHXpgc0i3dZSmjaO4eA9jetm9bG32irDdQGSifF27vv0m3X1GlgeIYtK2kZnUmxFBYadiGCGBk3+V78VKCLiTsB/G5b/9L70AaQmodPjYiOqmi2K5k6rMJ0lpP52ho3njN2oIvH7Ot4vNdc75qXlsHFX1VQfQlenxuzWszmlQQQAfQ+uj26rhftaKiYfPETPTztRHoRIeyYxqCnpNU5oGw3EcWQklxyNDVH0FqQ7H5iZw=
      distributions: sdist bdist_wheel
      on:
        tags: true
